### ISSUE TITLE
EF JS Team > Emergency Plan

### ISSUE THREAD

**Issue by nivida** [ethereum/js-team-organization#6]
Hey All! 

@cgewecke and I do currently improve the release process and started to define contribution rules. In the PR from Chris came the question up about emergencies and escalation plans and I think this should be something we have to define for all EF JS projects together.

Three points I thought about: 

- Is 24/7 possible?
- Permission management to release hotfixes?
- Clear escalation plan? (Who to contact and different escalation levels)

Happy to hear any input!

**Comment by holgerd77** [comment]
I think this very much make sense to integrate into future strategy discussions, all this is super-important and we operate rather on the low-end here on EthereumJS as well. We should take some concrete goals here into the 2020 roadmap, so that we have something to measure against after some time.

Some things might take some time (months) to implement especially if they need a somewhat stronger organizational backup to make sense (e.g. to always have 2-3 people who could quickly react on emergency cases and have a deep enough insight into a respective library).

But very much worth to start the discussion and sort out what we can improve on what timeframes.

Eventually we can also integrate some guidelines into some common docs here as well.

//cc @marcgarreau

**Comment by marcgarreau** [comment]
Some repos are more attractive targets than others. Maybe we can agree on a good baseline for all, then go beyond that where appropriate. Added the topic to the shared resource doc.

**Comment by nivida** [comment]
> We should take some concrete goals here into the 2020 roadmap, so that we have something to measure against after some time.

Sounds great! 

> to always have 2-3 people who could quickly react on emergency cases and have a deep enough insight into a respective library

Yes, this would require by side of a vacation plan and timezone plan also a architectural documentation for each project with the key points listed and explained.  

> Eventually we can also integrate some guidelines into some common docs here as well.

Yes, it would require guidelines to escalate correctly with different levels of emergencies.


I think the hardest points to improve are the architectural documentation for each project with his pain points if existing and to have the possibility to publish a package in case we reached an escalation level where a patch has to be published asap.

Does someone know a well-used emergency level concept?

**Comment by holgerd77** [comment]
Outdated, will close.
